spring:
  datasource:
    url: jdbc:mysql://localhost:3306/DXC_DEMO?useSSL=false&serverTimezone=UTC
    username: root
    password: password123
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: false