spring:
  datasource:
    url: jdbc:h2:mem:DXC_DEMO
    username: sa
    password:
    hikari:
      leak-detection-threshold: 2000
      #default maximum-pool-size:
      #default minimum-idle:
      #default idle-timeout:
      #default max-lifetime:
  h2:
    console:
      enabled: true