INSERT INTO USERS (NAME, USERNAME, PASSWORD, ROLE, CREATED_AT, UPDATED_AT)
SELECT 'John', 'admin', '$2a$10$AYZG2e/pEVK4V58w3iwkTej95wVF0o2S6jvV8tbnvX0vAbzNu5h3u', 'admin', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
    WHERE NOT EXISTS (
    SELECT 1 FROM USERS WHERE USERNAME = 'admin'
);

INSERT INTO USERS (NAME, USERNAME, PASSWORD, ROLE, CREATED_AT, UPDATED_AT)
SELECT 'Jane', 'manager', '$2a$10$OMqeqi9.lwSb9tDTuwfhEOCNRIaJSzv78chQfeb8LqCoIdvSYlTUO', 'manager', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
    WHERE NOT EXISTS (
    SELECT 1 FROM USERS WHERE USERNAME = 'manager'
);

INSERT INTO USERS (NAME, USERNAME, PASSWORD, ROLE, CREATED_AT, UPDATED_AT)
SELECT 'Jerry', 'user', '$2a$10$mxTxlPUyMOGVORiUDJsNruAj6ivqH86DcryP5zUpGQU5eYiCz3lVe', 'user', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
    WHERE NOT EXISTS (
    SELECT 1 FROM USERS WHERE USERNAME = 'user'
);
